### ISSUE TITLE
failing flips many coins

### ISSUE THREAD

**Issue by avmad22** [comp426-2022-spring/a03#12]
hi! i am passing every other test except flips many coins, but my output seems to match the autograders? im not sure what to do about this

**Comment by camsimba** [comment]
Hey @avmad22,

It looks like the output is slightly wrong compared to what is requested in the assignment instructions, at the end of the output with `"summary":"{ heads: 141, tails: 155 }"`, try taking out the quotation marks around { heads: 141, tails: 155 } and add quotation marks around 'heads' and 'tails' so that it looks like `"summary":{"heads":141,"tails":155}` and let me know if that works!

**Comment by avmad22** [comment]
it works! thank you!

**Comment by camsimba** [comment]
Glad I could help!
